name: Scan for Secrets

on:
  push:
    branches:
      - '**' # Перевіряти всі гілки

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      # Завантаження репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Встановлення Gitleaks
      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks

      # Запуск сканування на секрети
      - name: Scan for secrets with Gitleaks
        run: gitleaks detect --source . --report-path gitleaks-report.json --exit-code 1

      # Завантаження результатів сканування (опціонально)
      - name: Upload Gitleaks report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json
