name: Scan for Secrets with TruffleHog

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS Scan
        id: trufflehog
        uses: trufflesecurity/trufflehog@v1
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug --only-verified

      - name: Check for secrets and fail the job if found
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
