name: Checking for Secrets
on: push
env:
  SCANNER_ARGS: |
      --exclude-files \.github/actions/spelling/.*
      --exclude-lines ^\s+with\s+imageTag\s*=.*$
jobs:
  check-secrets:
    name: Checking for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Configuration
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install detect-secrets

      - name: Generate Baseline File
        run: detect-secrets scan > .secrets.baseline
        if: ${{ !contains(steps.baseline.outputs.baseline, 'baseline') }}

      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
        with:
          detect-secret-additional-args: ${{ env.SCANNER_ARGS }}
          baseline-file: .secrets.baseline
