name: Scan for Secrets with TruffleHog

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up commits comparison variables
        id: commits
        run: |
          BASE=$(git merge-base origin/main HEAD)
          HEAD=$(git rev-parse HEAD)
          echo "BASE commit: $BASE"
          echo "HEAD commit: $HEAD"
          echo "::set-output name=base_commit::$BASE"
          echo "::set-output name=head_commit::$HEAD"

      - name: Check if the BASE and HEAD commits are the same
        id: check_commits
        run: |
          if [ "${{ steps.commits.outputs.base_commit }}" == "${{ steps.commits.outputs.head_commit }}" ]; then
            echo "BASE and HEAD commits are the same. Skipping TruffleHog scan."
            exit 0
          fi

      - name: TruffleHog OSS Scan
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: "${{ steps.commits.outputs.base_commit }}"
          head: "${{ steps.commits.outputs.head_commit }}"
          extra_args: --debug --only-verified

      - name: Check for secrets and fail the job if found
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
