name: Scan for Secrets

on:
  push:
    branches:
      - '**' # Перевіряти всі гілки

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      # Завантаження репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Виконання сканування з Gitleaks
      - name: Scan for secrets with Gitleaks
        uses: zricethezav/gitleaks-action@v1
        with:
          args: detect --source . --report-path gitleaks-report.json --exit-code 1

      # Завантаження результатів сканування (опціонально)
      - name: Upload Gitleaks report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json
