name: Secret Scan on Push
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          scan_directory: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          extra_args: --json

      - name: Check TruffleHog Results
        if: always()
        run: |
          echo "Checking scan results..."
          if grep -q "Verified: true" trufflehog.log; then
            echo "Secrets found in the code!"
            exit 1
          else
            echo "No secrets found. Everything is good!"
          fi
