name: Full Secret Scan

on:
  push:
    branches:
      - '**'

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run grab/secret-scanner with full scan
        uses: grab/secrets-scanner@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_secrets: true
          scan_encrypted_secrets: true
          scan_all_file_types: true
          verbose: true
